### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hilem** [krakend/go-auth0#1]
Lot of great bug fixes upstream on [square/go-jose](https://github.com/square/go-jose/releases) including a number around JWKs which I'm currently hitting.

For added context, I'm hitting an issue with not being able to read some JWKs.
Here's one [example](https://api.userfront.com/v0/tenants/vbqqrqjb/jwks) in particular.
Stepped through with Delve and its blowing up attempting to decode the json.
Specifically on this [line](https://github.com/devopsfaith/go-auth0/blob/master/jwk_client.go#L100).
I noticed the go.mod file here is referring to an old `squre/go-jose` prior to a number of JWK fixes that were pushed.

**Comment by kpacha** [comment]
This repo is an immutable fork and the `square/go-jose` dep is updated at krakend-jose and krakend-ce.

Also, check your JWK because it is not compliant with the RFC (https://datatracker.ietf.org/doc/html/rfc7517). Check the definition of BASE64URL at section 1.1
